version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_biblioteca
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libros_bd
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
